# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from os import path

from actions.Action import Action

class ListItem(QtWidgets.QWidget):
    def __init__(self, parent, item : QtWidgets.QListWidgetItem):
        super(ListItem, self).__init__(parent)
        #self.setObjectName("self")
        self.connection = item

        self.gridLayout = QtWidgets.QHBoxLayout(self)
        self.gridLayout.setObjectName("gridLayout")

        self.actionImageDisplay = QtWidgets.QLabel(self)
        self.actionImageDisplay.setMinimumSize(QtCore.QSize(0, 10))
        self.actionImageDisplay.setObjectName("actionImageDisplay")
        self.gridLayout.addWidget(self.actionImageDisplay)

        self.commandDisplay = QtWidgets.QLabel(self)
        self.commandDisplay.setMinimumSize(QtCore.QSize(0, 10))
        self.commandDisplay.setObjectName("commandDisplay")
        self.gridLayout.addWidget(self.commandDisplay)

        self.deleteButton = QtWidgets.QPushButton(self)
        self.deleteButton.setMinimumSize(QtCore.QSize(0, 10))
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout.addWidget(self.deleteButton)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.actionImageDisplay.setText(_translate("self", "ImageLabel"))
        self.deleteButton.setText(_translate("self", "DeleteButton"))

    def completeInfo(self, action : Action):
        self.action = action
        self.actionImageDisplay.setPixmap(QtGui.QPixmap(action.iconPath))
        self.commandDisplay.setText(action.command)
        self.deleteButton.clicked.connect(self.onDelete)

    def onDelete(self):
        parent = self.connection.parent
        index = parent.row(self.connection)

        parent.takeItem(index)
        del parent.workSpace[index]

